
config:
  target: "http://localhost:4000"
  phases:
    - duration: 10
      arrivalRate: 1
scenarios:
  - flow:
      - post:
          url: '/login'
          json:
            login: "admin"
            password: "admin"
          capture:
            json: '$.token'
            as: 'token'
      - post:
          headers:
            authorization: 'Bearer {{token}}'
          url: '/users'
          json:
            login: "testing{{ $randomString(8) }}"
            name: "testing"
            password: "123456"
      - get:
          headers:
            authorization: 'Bearer {{token}}'
          url: '/users'
