version: '3.8'
services:
  node:
    container_name: 'node'
    image: 'uporold/rs-school:node'
    build: .
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./logs:/usr/app/logs
      - ./src:/usr/app/src
    restart: always
    environment:
      PORT: ${PORT}
    networks:
      - user-defined
  postgres:
    container_name: 'postgres'
    image: 'uporold/rs-school:postgres'
    build: ./db-dockerfile/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      PORT: ${PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
    networks:
      - user-defined

networks:
  user-defined:
    driver: bridge
